-- FIFA World Cup 2026 knockout bracket.
-- Run after schema.sql. Source: https://www.fifa.com/en/articles/knockout-stage-match-schedule-bracket

insert into public.bracket_matches (
  match_no,
  round_key,
  round_label,
  match_date,
  home_label,
  away_label,
  venue,
  city,
  source_url,
  display_order
)
values
  (73, 'round_of_32', 'Round of 32', '2026-06-28', 'Group A runners-up', 'Group B runners-up', 'Los Angeles Stadium', 'Los Angeles', 'https://www.fifa.com/en/articles/knockout-stage-match-schedule-bracket', 73),
  (74, 'round_of_32', 'Round of 32', '2026-06-29', 'Group E winners', 'Group A/B/C/D/F third place', 'Boston Stadium', 'Boston', 'https://www.fifa.com/en/articles/knockout-stage-match-schedule-bracket', 74),
  (75, 'round_of_32', 'Round of 32', '2026-06-29', 'Group F winners', 'Group C runners-up', 'Estadio Monterrey', 'Monterrey', 'https://www.fifa.com/en/articles/knockout-stage-match-schedule-bracket', 75),
  (76, 'round_of_32', 'Round of 32', '2026-06-29', 'Group C winners', 'Group F runners-up', 'Houston Stadium', 'Houston', 'https://www.fifa.com/en/articles/knockout-stage-match-schedule-bracket', 76),
  (77, 'round_of_32', 'Round of 32', '2026-06-30', 'Group I winners', 'Group C/D/F/G/H third place', 'New York New Jersey Stadium', 'New York/New Jersey', 'https://www.fifa.com/en/articles/knockout-stage-match-schedule-bracket', 77),
  (78, 'round_of_32', 'Round of 32', '2026-06-30', 'Group E runners-up', 'Group I runners-up', 'Dallas Stadium', 'Dallas', 'https://www.fifa.com/en/articles/knockout-stage-match-schedule-bracket', 78),
  (79, 'round_of_32', 'Round of 32', '2026-06-30', 'Group A winners', 'Group C/E/F/H/I third place', 'Mexico City Stadium', 'Mexico City', 'https://www.fifa.com/en/articles/knockout-stage-match-schedule-bracket', 79),
  (80, 'round_of_32', 'Round of 32', '2026-07-01', 'Group L winners', 'Group E/H/I/J/K third place', 'Atlanta Stadium', 'Atlanta', 'https://www.fifa.com/en/articles/knockout-stage-match-schedule-bracket', 80),
  (81, 'round_of_32', 'Round of 32', '2026-07-01', 'Group D winners', 'Group B/E/F/I/J third place', 'San Francisco Bay Area Stadium', 'San Francisco Bay Area', 'https://www.fifa.com/en/articles/knockout-stage-match-schedule-bracket', 81),
  (82, 'round_of_32', 'Round of 32', '2026-07-01', 'Group G winners', 'Group A/E/H/I/J third place', 'Seattle Stadium', 'Seattle', 'https://www.fifa.com/en/articles/knockout-stage-match-schedule-bracket', 82),
  (83, 'round_of_32', 'Round of 32', '2026-07-02', 'Group K runners-up', 'Group L runners-up', 'Toronto Stadium', 'Toronto', 'https://www.fifa.com/en/articles/knockout-stage-match-schedule-bracket', 83),
  (84, 'round_of_32', 'Round of 32', '2026-07-02', 'Group H winners', 'Group J runners-up', 'Los Angeles Stadium', 'Los Angeles', 'https://www.fifa.com/en/articles/knockout-stage-match-schedule-bracket', 84),
  (85, 'round_of_32', 'Round of 32', '2026-07-02', 'Group B winners', 'Group E/F/G/I/J third place', 'BC Place Vancouver', 'Vancouver', 'https://www.fifa.com/en/articles/knockout-stage-match-schedule-bracket', 85),
  (86, 'round_of_32', 'Round of 32', '2026-07-03', 'Group J winners', 'Group H runners-up', 'Miami Stadium', 'Miami', 'https://www.fifa.com/en/articles/knockout-stage-match-schedule-bracket', 86),
  (87, 'round_of_32', 'Round of 32', '2026-07-03', 'Group K winners', 'Group D/E/I/J/L third place', 'Kansas City Stadium', 'Kansas City', 'https://www.fifa.com/en/articles/knockout-stage-match-schedule-bracket', 87),
  (88, 'round_of_32', 'Round of 32', '2026-07-03', 'Group D runners-up', 'Group G runners-up', 'Dallas Stadium', 'Dallas', 'https://www.fifa.com/en/articles/knockout-stage-match-schedule-bracket', 88),
  (89, 'round_of_16', 'Round of 16', '2026-07-04', 'Winner match 74', 'Winner match 77', 'Philadelphia Stadium', 'Philadelphia', 'https://www.fifa.com/en/articles/knockout-stage-match-schedule-bracket', 89),
  (90, 'round_of_16', 'Round of 16', '2026-07-04', 'Winner match 73', 'Winner match 75', 'Houston Stadium', 'Houston', 'https://www.fifa.com/en/articles/knockout-stage-match-schedule-bracket', 90),
  (91, 'round_of_16', 'Round of 16', '2026-07-05', 'Winner match 76', 'Winner match 78', 'New York New Jersey Stadium', 'New York/New Jersey', 'https://www.fifa.com/en/articles/knockout-stage-match-schedule-bracket', 91),
  (92, 'round_of_16', 'Round of 16', '2026-07-05', 'Winner match 79', 'Winner match 80', 'Mexico City Stadium', 'Mexico City', 'https://www.fifa.com/en/articles/knockout-stage-match-schedule-bracket', 92),
  (93, 'round_of_16', 'Round of 16', '2026-07-06', 'Winner match 83', 'Winner match 84', 'Dallas Stadium', 'Dallas', 'https://www.fifa.com/en/articles/knockout-stage-match-schedule-bracket', 93),
  (94, 'round_of_16', 'Round of 16', '2026-07-06', 'Winner match 81', 'Winner match 82', 'Seattle Stadium', 'Seattle', 'https://www.fifa.com/en/articles/knockout-stage-match-schedule-bracket', 94),
  (95, 'round_of_16', 'Round of 16', '2026-07-07', 'Winner match 86', 'Winner match 88', 'Atlanta Stadium', 'Atlanta', 'https://www.fifa.com/en/articles/knockout-stage-match-schedule-bracket', 95),
  (96, 'round_of_16', 'Round of 16', '2026-07-07', 'Winner match 85', 'Winner match 87', 'BC Place Vancouver', 'Vancouver', 'https://www.fifa.com/en/articles/knockout-stage-match-schedule-bracket', 96),
  (97, 'quarter_final', 'Quarter-finals', '2026-07-09', 'Winner match 89', 'Winner match 90', 'Boston Stadium', 'Boston', 'https://www.fifa.com/en/articles/knockout-stage-match-schedule-bracket', 97),
  (98, 'quarter_final', 'Quarter-finals', '2026-07-10', 'Winner match 93', 'Winner match 94', 'Los Angeles Stadium', 'Los Angeles', 'https://www.fifa.com/en/articles/knockout-stage-match-schedule-bracket', 98),
  (99, 'quarter_final', 'Quarter-finals', '2026-07-11', 'Winner match 91', 'Winner match 92', 'Miami Stadium', 'Miami', 'https://www.fifa.com/en/articles/knockout-stage-match-schedule-bracket', 99),
  (100, 'quarter_final', 'Quarter-finals', '2026-07-11', 'Winner match 95', 'Winner match 96', 'Kansas City Stadium', 'Kansas City', 'https://www.fifa.com/en/articles/knockout-stage-match-schedule-bracket', 100),
  (101, 'semi_final', 'Semi-finals', '2026-07-14', 'Winner match 97', 'Winner match 98', 'Dallas Stadium', 'Dallas', 'https://www.fifa.com/en/articles/knockout-stage-match-schedule-bracket', 101),
  (102, 'semi_final', 'Semi-finals', '2026-07-15', 'Winner match 99', 'Winner match 100', 'Atlanta Stadium', 'Atlanta', 'https://www.fifa.com/en/articles/knockout-stage-match-schedule-bracket', 102),
  (103, 'third_place', 'Third-place play-off', '2026-07-18', 'Runner-up match 101', 'Runner-up match 102', 'Miami Stadium', 'Miami', 'https://www.fifa.com/en/articles/knockout-stage-match-schedule-bracket', 103),
  (104, 'final', 'Final', '2026-07-19', 'Winner match 101', 'Winner match 102', 'New York New Jersey Stadium', 'New York/New Jersey', 'https://www.fifa.com/en/articles/knockout-stage-match-schedule-bracket', 104)
on conflict (match_no) do update
set round_key = excluded.round_key,
    round_label = excluded.round_label,
    match_date = excluded.match_date,
    home_label = excluded.home_label,
    away_label = excluded.away_label,
    venue = excluded.venue,
    city = excluded.city,
    source_url = excluded.source_url,
    display_order = excluded.display_order,
    updated_at = now();
